SELECT i.ANIMAL_ID,i.ANIMAL_TYPE,i.NAME FROM ANIMAL_INS i WHERE i.SEX_UPON_INTAKE LIKE 'Intact%'
INTERSECT
SELECT o.ANIMAL_ID,o.ANIMAL_TYPE,o.NAME FROM ANIMAL_OUTS o WHERE o.SEX_UPON_OUTCOME LIKE 'Spayed%' OR o.SEX_UPON_OUTCOME LIKE 'Neutered%';