SELECT DATE_FORMAT(w.START_DATE, '%c') AS MONTH, w.CAR_ID, COUNT(w.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY w
WHERE
    w.START_DATE >= '2022-08-01'
    AND w.START_DATE < '2022-11-01'
    AND w.CAR_ID IN (
        SELECT c.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
        WHERE
            c.START_DATE >= '2022-08-01'
            AND c.START_DATE < '2022-11-01'
        GROUP BY c.CAR_ID
        HAVING COUNT(c.CAR_ID) >= 5
    )
GROUP BY MONTH, w.CAR_ID
ORDER BY MONTH(w.START_DATE) ASC, CAR_ID DESC;
