-- 코드를 입력하세요
SELECT c.CAR_ID FROM CAR_RENTAL_COMPANY_CAR c
WHERE c.CAR_TYPE='세단' AND c.CAR_ID IN (SELECT h.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE h.START_DATE>=TO_DATE('20221001', 'YYYYMMDD'))
ORDER BY c.CAR_ID DESC;